language: ruby
cache: bundler
rvm:
  - 2.6

install:
  - bundle install

before_script:
  - if [ "$TRAVIS_BRANCH" == "production" ]; then export JEKYLL_ENV=production; fi
  - bundle exec jekyll build -d public

# https://docs.travis-ci.com/user/build-stages
jobs:
  include:
    - stage: test
      name: JSON Schemas
      script:
        - bundle exec rake tests:schemas
    - stage: test
      name : Liens
      script:
        - bundle exec rake tests:liens_public
    - stage: deploy
      name: Déploiement de production
      script:
        - echo "Déploiement"
      deploy:
        local_dir: public
        target_branch: master
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: production

stages:
  - test
  - name: deploy
    if: branch = "production"
