title: CyberQuébec.org
author:
  fr: CCTT en cybersécurité du Cégep de l'Outaouais
  en: CCTT in cybersecurity of Cégep de l'Outaouais
description:
  fr: CCTT en cybersécurité du Cégep de l'Outaouais
  en: CCTT in cybersecurity of Cégep de l'Outaouais

url: https://cyberquebec.org
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
keep_files:
  - css
strict-front-matter: true

languages: ["fr", "en"]
default_lang: "fr"
exclude_from_localization:
  - assets/*
  - favicon.ico
parallel_localization: false # Cette fonction doit être désactivée, car elle ne fonctionne pas sur Windows

jekyll-minifier:
  exclude:
    - assets/fontawesome/*
  uglifier_args:
    harmony: true # Permet d'utiliser la syntaxe ES6

link-checker:
  skip-list:
    - https://haveibeenpwned.com/
    - https://teksavvy.com/
    - https://www.nce-rce.gc.ca/

collections:
  sources:
    layout: source
    output: true
    permalink: /trousse/sources/:path/
    sous-section: sources
  pratiques:
    layout: pratique
    output: true
    permalink: /trousse/pratiques/:path/
    sous-section: pratiques
  risques:
    layout: risques
    output: true
    permalink: /trousse/risques/:path/
    sous-section: risques
  faq:
    layout: faq
    output: false
    sous-section: faq
  conferences:
    layout: conferences
    output: true
    sous-section: conferences
  posts:
    permalink: /blog/:title/

# Valeurs par défaut pour front matters
defaults:
  - scope:
      path: "" # Tous les fichiers du projet
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: article
  - scope:
      path: "_sources"
    values:
      layout: source
      stylesheets:
        - sources.css
  - scope:
      path: "_pratiques"
    values:
      layout: pratique
      stylesheets:
        - pratique.css
  - scope:
      path: "_risques"
    values:
      layout: risque
      stylesheets:
        - risque.css

schema-checker:
  skip:
    - "*/README.md"
    - "*/TODO.md"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-polyglot
